# Generated by Django 6.0.4 on 2026-04-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="joined_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="members",
            name="phone",
            field=models.IntegerField(null=True),
        ),
    ]
